user_file = ".streamlit/users.yaml"
data_file = "data.json"
checklist_template_file = "checklist_template.json"
gui = "75674c19-0ca1-4fd3-acff-9341001cd159"
url = "https://abr.business.gov.au/json/AbnDetails.aspx?"